### ISSUE TITLE
Error on build - dependency to Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by folbrecht** [christianhelle/refitter#233] opened 2023-12-07 16:43 UTC
REFITTER000	System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Systém nemůže nalézt uvedený soubor.

I tried to install package Microsoft.Bcl.AsyncInterfaces, but it did not help. VS 2022, MAUI app project. 
Thanks for help

**Comment by christianhelle** [comment] 2023-12-08 08:21
@all-contributors please add @folbrecht for bugs

**Comment by christianhelle** [comment] 2023-12-10 22:39
@folbrecht I could easily reproduce your problem, but I haven't figured out why this happens with MAUI projects. 

One good thing is that Refit itself works fine with MAUI but the `Refitter.SourceGenerator` package reference is causing the problems. 

As a workaround, you can remove the `Refitter.SourceGenerator` package reference and add the `Refit` package reference. Then you can keep the generated file as it is or re-generate it using the Refitter CLI tool

My schedule is a bit packed these days leading up to the holidays. I'll eventually, and hopefully, figure out what's wrong when working with MAUI, and work on a fix for the problem. Until then, I apologize for the inconvenience and the delays

**Comment by folbrecht** [comment] 2023-12-13 08:28
Thank you for your efforts. Jan

ne 10. 12. 2023 v 23:39 odesílatel Christian Helle ***@***.***>
napsal:

**Comment by manuel-fernandez-rodriguez** [comment] 2023-12-13 13:26
> REFITTER000 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Systém nemůže nalézt uvedený soubor.
> 
> I tried to install package Microsoft.Bcl.AsyncInterfaces, but it did not help. VS 2022, MAUI app project. Thanks for help

I have run into exactly the same problem on compiling, but it seems not be MAUI related (or, at least, not exclusively), because my project was a Web API and the build error occurred when building a class library, which was the project the nuget package was added to.

**Comment by christianhelle** [comment] 2023-12-13 14:06
> > REFITTER000 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Systém nemůže nalézt uvedený soubor.
> > I tried to install package Microsoft.Bcl.AsyncInterfaces, but it did not help. VS 2022, MAUI app project. Thanks for help
> 
> I have run into exactly the same problem on compiling, but it seems not be MAUI related (or, at least, not exclusively), because my project was a Web API and the build error occurred when building a class library, which was the project the nuget package was added to.

Interesting... I primarily use this myself on Web API (Minimal API) projects. What version of .NET do you target and what version of Refitter do you use?

I just put this little Minimal API project together to test it out:
[MinimalApi.zip](https://github.com/christianhelle/refitter/files/13661571/MinimalApi.zip)

I could build and run it without any issues

**Comment by manuel-fernandez-rodriguez** [comment] 2023-12-13 19:51
> > > REFITTER000 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Systém nemůže nalézt uvedený soubor.
> > > I tried to install package Microsoft.Bcl.AsyncInterfaces, but it did not help. VS 2022, MAUI app project. Thanks for help
> > 
> > 
> > I have run into exactly the same problem on compiling, but it seems not be MAUI related (or, at least, not exclusively), because my project was a Web API and the build error occurred when building a class library, which was the project the nuget package was added to.
> 
> @manuel-fernandez-rodriguez Interesting... I primarily use this myself on Web API (Minimal API) projects. What version of .NET do you target and what version of Refitter do you use?
> 
> I just put this little Minimal API project together to test it out: [MinimalApi.zip](https://github.com/christianhelle/refitter/files/13661571/MinimalApi.zip)
> 
> I could build and run it without any issues


I have downloaded the zip, and the openapi definition for the PetStore was missing, so I downloaded it from https://petstore3.swagger.io/api/v3/openapi.json.

The Refit interface was successfully generated, but I get exactly the same error that we have been mentioning from the start:

```
Build started at 20:44...
1>------ Build started: Project: MinimalApi, Configuration: Debug Any CPU ------
1>CSC : error REFITTER000: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
1>Done building project "MinimalApi.csproj" -- FAILED.
```

Surprisingly, if I build it from the command line:

```
> dotnet build
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  MinimalApi -> C:\Users\mfernandezr\Downloads\MinimalApi\bin\Debug\net8.0\MinimalApi.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.75
```

So I have to presume the problem is not the code itself, but something related to Visual Studio or its interaction with the code generation. 

My Visual Studio version is:
```
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.8.3
```
And I have the following SDK and runtimes installed:
```
> dotnet --list-sdks && dotnet --list-runtimes

8.0.100 [C:\Program Files\dotnet\sdk]
Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]```

**Comment by christianhelle** [comment] 2023-12-13 20:14
@manuel-fernandez-rodriguez Thanks for all the input! This will be very helpful. 

My excuse for not running into this - I spend most of my day in JetBrains Rider and the CLI 😞 

I'll see what I can do

**Comment by christianhelle** [comment] 2023-12-13 22:09
@manuel-fernandez-rodriguez Good news is that I found the [line of code](https://github.com/christianhelle/refitter/blob/9d6609c37c55bd1d389e0d93c35a2d8fb89c3c19/src/Refitter.SourceGenerator/RefitterSourceGenerator.cs#L70) that throws an exception. The bad news is that I don't understand why it does, and why it doesn't...

For now, I think I'll add a try/catch around the deserialization code in the source generator project and just jump out if anything unexpected happens

**Comment by christianhelle** [comment] 2023-12-13 22:11
@all-contributors please add @manuel-fernandez-rodriguez for bugs

**Comment by christianhelle** [comment] 2023-12-14 07:16
I released a **preview** version to NuGet

```xml
<PackageReference Include="Refitter.SourceGenerator" Version="0.8.6.38-preview" />
```

It works for me in my Visual Studio setup. Can you also try it on your machines @manuel-fernandez-rodriguez @folbrecht ?

**Comment by manuel-fernandez-rodriguez** [comment] 2023-12-14 17:35
@christianhelle 
Checked and, apparently it works flawlessly when building :)

Thank you SO much for the quick workaround.

**Comment by christianhelle** [comment] 2023-12-15 09:59
@folbrecht I tested the latest release preview on a new MAUI app and it seems to work fine. 

I'm closing this

**Closed by christianhelle** 2023-12-15 09:59 UTC
Labels: bug
